version: '3'
services:
    #PHP Service
    php-unit-test-app:
        build:
            context: ./docker/php
        container_name: php-unit-test-app
        restart: unless-stopped
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./xdebug/:/tmp/xdebug/
        networks:
            - app-network
    #Nginx Service
    php-unit-test-webserver:
        image: nginx:alpine
        container_name: php-unit-test-webserver
        restart: unless-stopped
        depends_on:
            - php-unit-test-app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
#Docker Networks
networks:
    app-network:
        driver: bridge
